In [6]:
import numpy as np
#single dimensional array
n1 = np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [8]:
#multiple dimensional array
n2 = np.array([[10,20,30,40],[40,50,60,70]])
n2

array([[10, 20, 30, 40],
       [40, 50, 60, 70]])

In [11]:
#initializing numpy array with zero

n3 = np.zeros((5,3))
n3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
#initializing numpy array with the same number usning a number
n4 = np.full((2,2),10)
n4

array([[10, 10],
       [10, 10]])

In [14]:
# initializing numpy array with in a range: it counts a number but would not add the last 
n5 = np.arange(10,20)
n5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
n6 =np.arange(10,50,5)
n6

array([10, 15, 20, 25, 30, 35, 40, 45])

In [16]:
#choicing diffirente numbers in a set
n7 = np.random.randint(1,100,5)
n7
#5 shows it will only choice 5 numbers out 100 numbers

array([49, 12, 54, 47,  3])

In [17]:
#using a shape to check how many list in the array and the item in the list
n8 = np.array([[1,2,3],[4,5,6]])
n8.shape

(2, 3)

In [22]:
#changing the shape
n8.shape = (3,2)
n8

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
# joining numpy arrays using :: vstack for verticals joining:: hstack for horizontal adding
f1 = np.array([10,20,30,40])
f2 = np.array([40,50,60])

np.vstack((f1,f2))

array([[10, 20, 30],
       [40, 50, 60]])

In [26]:
#using it to make the  only one list 
np.hstack((f1,f2))

array([10, 20, 30, 40, 50, 60])

In [27]:
#using columns_stack() it all list into one tag
np.column_stack((f1,f2))


array([[10, 40],
       [20, 50],
       [30, 60]])

In [35]:
#using intersaction and differences
np.intersect1d(f1,f2)


array([], dtype=int32)

In [39]:
import numpy as np
#using differences 
np.setdiff1d(f1,f2)

array([10, 20, 30])

In [40]:
#addition in numpy
np.sum([f1,f2])

210

In [42]:
# adding the list vertical
r1 = np.array([10,20,30])
r2 = np.array([40,50,60])
np.sum([r1,r2], axis = 0)

array([50, 70, 90])

In [43]:
np.sum([r1,r2], axis = 1)

array([ 60, 150])

In [44]:
#addition
r3 = r1 + 3
r3

array([13, 23, 33])

In [46]:
#multiplication
r4 = r2 * 2
r4

array([ 80, 100, 120])

In [47]:
#substraction 
r5 = r4 -2
r5

array([ 78,  98, 118])

In [48]:
#division 
r6 =  r5/2
r6

array([39., 49., 59.])

In [50]:
#checking the mean
np.mean(r6)

49.0

In [51]:
#standard deviation
np.std(r6)

8.16496580927726

In [58]:
# saving and loading numpy array
j1 = np.array([11,22,33,44,55,77])
np.save("my_num", j1)
r7= np.load("my_num.npy")
r7

array([11, 22, 33, 44, 55, 77])

In [59]:
# creating a series 
import pandas as pd
s1 = pd.Series([1,2,3,4,5])
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [60]:
type(s1)

pandas.core.series.Series

In [61]:
# setting the  index 
s2 = pd.Series([1,2,3,4,5],["a","b","c","d","e"])
s2

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [64]:
pd.Series({"a":10,"b":20,"c":30}, index=["c","b","a"])

c    30
b    20
a    10
dtype: int64

In [65]:
s2[2]

3

In [66]:
s2[:2]

a    1
b    2
dtype: int64

In [67]:
s2[-2:]

d    4
e    5
dtype: int64

In [68]:
s3 = s1 + s2
s3

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
a   NaN
b   NaN
c   NaN
d   NaN
e   NaN
dtype: float64

In [76]:
#using the dataframe in pandas

pd.DataFrame({"Name":["bob", "sam","Anne"], "Marks": [23, 47, 28]}) 


Name  Marks
0   bob     23
1   sam     47
2  Anne     28

In [77]:
iris = pd.read_csv("iris.csv")
iris

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [78]:
iris.tail()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [79]:
iris.describe()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [80]:
iris.shape

(150, 5)

In [81]:
#extracting individual roles and coulumns from data frame
iris.iloc[0:3,0:2]

Sepal.Length  Sepal.Width
0           5.1          3.5
1           4.9          3.0
2           4.7          3.2

In [84]:
# it those note have index
iris.loc[0:3,("Sepal.Length","Petal.Length")]
#iris.loc[0:3,("Sepal.Length","Petal.Length")]

Sepal.Length  Petal.Length
0           5.1           1.4
1           4.9           1.4
2           4.7           1.3
3           4.6           1.5

In [87]:
iris.drop("Sepal.Length",axis = 1)

Sepal.Width  Petal.Length  Petal.Width    Species
0            3.5           1.4          0.2     setosa
1            3.0           1.4          0.2     setosa
2            3.2           1.3          0.2     setosa
3            3.1           1.5          0.2     setosa
4            3.6           1.4          0.2     setosa
..           ...           ...          ...        ...
145          3.0           5.2          2.3  virginica
146          2.5           5.0          1.9  virginica
147          3.0           5.2          2.0  virginica
148          3.4           5.4          2.3  virginica
149          3.0           5.1          1.8  virginica

[150 rows x 4 columns]

In [88]:
iris.drop(([1,2,3]), axis = 0)

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
5             5.4          3.9           1.7          0.4     setosa
6             4.6          3.4           1.4          0.3     setosa
7             5.0          3.4           1.5          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[147 rows x 5 columns]

In [89]:
iris.median()

Sepal.Length    5.80
Sepal.Width     3.00
Petal.Length    4.35
Petal.Width     1.30
dtype: float64

In [90]:
iris.min()

Sepal.Length       4.3
Sepal.Width          2
Petal.Length         1
Petal.Width        0.1
Species         setosa
dtype: object

In [91]:
def half(s):
    return s * 0.5
iris[["Sepal.Length","Petal.Length"]].apply(half)

Sepal.Length  Petal.Length
0            2.55          0.70
1            2.45          0.70
2            2.35          0.65
3            2.30          0.75
4            2.50          0.70
..            ...           ...
145          3.35          2.60
146          3.15          2.50
147          3.25          2.60
148          3.10          2.70
149          2.95          2.55

[150 rows x 2 columns]

In [92]:
#using value_count
iris["Species"].value_counts()

virginica     50
setosa        50
versicolor    50
Name: Species, dtype: int64

In [93]:
#using sort_values 
iris.sort_values(by="Sepal.Length")

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
13            4.3          3.0           1.1          0.1     setosa
42            4.4          3.2           1.3          0.2     setosa
38            4.4          3.0           1.3          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
41            4.5          2.3           1.3          0.3     setosa
..            ...          ...           ...          ...        ...
122           7.7          2.8           6.7          2.0  virginica
118           7.7          2.6           6.9          2.3  virginica
117           7.7          3.8           6.7          2.2  virginica
135           7.7          3.0           6.1          2.3  virginica
131           7.9          3.8           6.4          2.0  virginica

[150 rows x 5 columns]